openapi: 3.0.3
info:
  version: 1.1.2
  title: NLP Sandbox PHI Annotator API
  contact:
    name: NLP Sandbox Team
    email: team@nlpsandbox.io
    url: https://nlpsandbox.io
  license:
    name: Apache 2.0
    url: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/main/LICENSE
  x-logo:
    url: https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png
  description: >
    # Introduction

    A protected health information (PHI) annotator implements several endpoints
    that take as input a clinical note and outputs a list of predicted PHI
    annotations found in the clinical note. This OpenAPI document describes the
    specification of the NLP Sandbox PHI Annotator API. This specification
    includes the schemas of the input and output data, and the requirements that
    this annotator must meet if you want to benchmark its performance on
    [nlpsandbox.io](https://nlpsandbox.io).

    # Getting Started

    The GitHub repository
    [nlpsandbox/phi-annotator-example](https://github.com/nlpsandbox/phi-annotator-example)
    provides an example implementation of the NLP Sandbox PHI Annotator API in
    Python-Flask. By the end of the tutorial available in the README, you will
    have built a Docker image for this NLP Sandbox tool. You will then be able
    to submit this image to [nlpsandbox.io](https://nlpsandbox.io) to benchmark
    its performance.

    # Benchmarking Requirements

    Your NLP Sandbox tool must meet the following requirements before evaluating
    its performance on [nlpsandbox.io](https://nlpsandbox.io).

    - The endpoint `/` must redirect to `/api/v1/tool`.

    - The endpoint `/ui` must redirect to the Swagger User Interface (UI).

    - The output of this tool must be reproducible: a given input should always
      generate the same output.

    - To ensure the results are reproducible and robust, and the data are
      secured, this tool must not connect to any remote server. When benchmarked
      on [nlpsandbox.io](https://nlpsandbox.io), this tool will not be able to
      connect to remote servers.

    # Examples

    - [NLP Sandbox PHI Annotator Example (Python)](https://github.com/nlpsandbox/phi-annotator-example)
tags:
  - name: HealthCheck
    description: Operations about health checks
  - name: TextContactAnnotation
    description: Operations about text contact annotations
  - name: TextDateAnnotation
    description: Operations about text date annotations
  - name: TextIdAnnotation
    description: Operations about text ID annotations
  - name: TextPersonNameAnnotation
    description: Operations about text person name annotations
  - name: TextLocationAnnotation
    description: Operations about text location annotations
  - name: Tool
    description: Operations about this tool
servers:
  - url: http://example.com/api/v1
  - url: https://example.com/api/v1
paths:
  /healthCheck:
    $ref: ../commons/paths/healthCheck.yaml
  /textContactAnnotations:
    $ref: ../contact-annotator/paths/textContactAnnotations.yaml
  /textDateAnnotations:
    $ref: ../date-annotator/paths/textDateAnnotations.yaml
  /textIdAnnotations:
    $ref: ../id-annotator/paths/textIdAnnotations.yaml
  /textLocationAnnotations:
    $ref: ../location-annotator/paths/textLocationAnnotations.yaml
  /textPersonNameAnnotations:
    $ref: ../person-name-annotator/paths/textPersonNameAnnotations.yaml
  /tool:
    $ref: ../commons/paths/tool.yaml
  /tool/dependencies:
    $ref: ../commons/paths/dependencies.yaml
