openapi: 3.0.3
info:
  version: 1.1.1
  title: NLP Sandbox Tool API
  contact:
    name: NLP Sandbox Team
    email: team@nlpsandbox.io
    url: https://nlpsandbox.io
  license:
    name: Apache 2.0
    url: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/LICENSE
  x-logo:
    url: https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png
  description: |
    OpenAPI specification that groups the specs of all the NLP Sanbox tools.
tags:
  - name: HealthCheck
    description: Operations about health checks
  - name: Tool
    description: Operations about this tool
paths:
  /healthCheck:
    $ref: ../../commons/paths/healthCheck.yaml
  /tool:
    $ref: ../../commons/paths/tool.yaml
  /tool/dependencies:
    $ref: ../../commons/paths/dependencies.yaml
